# Generated by Django 5.2.3 on 2025-06-26 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('agency_logo', models.ImageField(blank=True, upload_to='agency-logo')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='customer-profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('owner_photo', models.ImageField(blank=True, upload_to='owner-profile')),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('home', 'Home'), ('apartment', 'Apartment'), ('hostel', 'Hostel Room')], max_length=20)),
                ('beds', models.PositiveIntegerField()),
                ('bath', models.PositiveIntegerField()),
                ('wi_fi', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('main_photo', models.ImageField(upload_to='properties')),
                ('bed_photo', models.ImageField(blank=True, upload_to='properties')),
                ('bath_photo', models.ImageField(blank=True, upload_to='properties')),
                ('pool_photo', models.ImageField(blank=True, upload_to='properties')),
                ('rent_type', models.CharField(choices=[('Month', 'Rent per Month'), ('YEAR', 'Rent per Year')], max_length=20)),
                ('rent_amount', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('rented', 'Rented')], max_length=20)),
                ('description', models.TextField()),
                ('review_star', models.CharField(max_length=3)),
                ('review_comment', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.city')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='myapp.region'),
        ),
    ]
