# Generated by Django 5.2.1 on 2025-07-31 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_review_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('sender_subject', models.CharField(blank=True, max_length=15, null=True)),
                ('sender_message', models.TextField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
