# Generated by Django 5.2.1 on 2025-08-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_customuser_phone_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer_name',
            new_name='customer_full_name',
        ),
    ]
