# Generated by Django 5.2.1 on 2025-08-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_agencyprofile_email_agencyprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='is_replied',
            new_name='is_purchased',
        ),
    ]
