# Generated by Django 5.2.1 on 2025-08-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_is_replied_inquiry_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='myapp.property'),
        ),
    ]
