# Generated by Django 5.2.1 on 2025-08-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_inquiry_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CUSTOMER', 'Customer'), ('AGENCY', 'Agency')], default='CUSTOMER', max_length=20),
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
    ]
